### ISSUE TITLE
Create method always return undefined.

### ISSUE THREAD

**Issue by cesarvspr** [vposd/ts-randomizer#102]
Code sample:

```ts
interface foo {
  data: string;
}

  const response = Randomizer.create<foo>();
  console.log(response);

```

Expected: A object with type `foo`

Actual status: Console.log() prints undefined.

**Comment by vposd** [comment]
Hello, Caesar,
There is the test for this case, it works. Also, there is an example setup for jest with the same case, please take a look at  `examples/jest`.

According to readme, the ts-randomiser contains two parts - typescript plugin and Randomiser class.
I assume you maybe forgot about the typescript plugin setup.
Please, take a look for `examples/jest`, the `tsconfig.json`.

**Comment by cesarvspr** [comment]
Thanks for your reply @vposd now I understand that jest example contains the correct setup, but it should be easier to understand to have the tsconfig.json needed setup inside the main readme or inside /jest. What you think about it?

**Comment by cesarvspr** [comment]
I just found https://github.com/vposd/ts-randomizer/blob/master/docs/TRANSFORMER.md 

I think this issue can be closed, tks again! @vposd
